import { Category } from '@prisma/client';
import { ECategoryType } from '../../src/modules/category/category.enum';

const categories: Category[] = [
  {
    id: `C_1`,
    nameEn: 'Mortgage / Rent',
    nameVn: 'Thế chấp / Tiền thuê nhà',
    type: ECategoryType.MORTGAGE,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_2`,
    nameEn: 'Food',
    nameVn: 'Thực phẩm',
    type: ECategoryType.FOOD,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_3`,
    nameEn: 'Utilities',
    nameVn: 'Tiện ích',
    type: ECategoryType.UTILITIES,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_4`,
    nameEn: 'Bills',
    nameVn: 'Hóa đơn',
    type: ECategoryType.BILLS,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_5`,
    nameEn: 'Shopping',
    nameVn: 'Mua sắm',
    type: ECategoryType.SHOPPING,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_6`,
    nameEn: 'Transportation',
    nameVn: 'Di chuyển',
    type: ECategoryType.TRANSPORTATION,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_7`,
    nameEn: 'Insurance',
    nameVn: 'Bảo hiểm',
    type: ECategoryType.INSURANCE,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_8`,
    nameEn: 'Health Care',
    nameVn: 'Chăm sóc sức khỏe',
    type: ECategoryType.HEALTHCARE,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_9`,
    nameEn: 'Clothing',
    nameVn: 'Quần áo',
    type: ECategoryType.CLOTHING,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: `C_10`,
    nameEn: 'Others',
    nameVn: 'Khác',
    type: ECategoryType.OTHERS,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default categories;
