import { Transaction } from '@prisma/client';
import { ECashflow, EPaymentMode } from '../../src/modules/transaction/transaction.enum';

const transactions: Transaction[] = [
  // Jan
  {
    id: 'T_1',
    amount: 3500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_2',
    amount: 1100000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_3',
    amount: 160000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_4',
    amount: 450000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_5',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_6',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: 'T_7',
    amount: 13500000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  // Feb
  {
    id: 'T_8',
    amount: 3800000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_9',
    amount: 750000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_10',
    amount: 150000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_11',
    amount: 400000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_12',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_13',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: 'T_14',
    amount: 13400000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
  },
  // Mar
  {
    id: 'T_15',
    amount: 3000000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_16',
    amount: 8500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_17',
    amount: 165000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_18',
    amount: 420000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_19',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_20',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: 'T_21',
    amount: 13200000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  // Apirl
  {
    id: 'T_22',
    amount: 3200000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_23',
    amount: 7300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_24',
    amount: 150000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_25',
    amount: 350000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_26',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_27',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: 'T_28',
    amount: 11500000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  // May
  {
    id: 'T_29',
    amount: 3300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_30',
    amount: 1100000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_31',
    amount: 155000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_32',
    amount: 380000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_33',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_34',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: 'T_35',
    amount: 13400000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  // Jun
  {
    id: 'T_36',
    amount: 3800000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_37',
    amount: 1050000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_38',
    amount: 180000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_39',
    amount: 430000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_40',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_41',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: 'T_42',
    amount: 12300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  // Jul
  {
    id: 'T_43',
    amount: 3600000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_44',
    amount: 8300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_45',
    amount: 165000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_46',
    amount: 425000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_47',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_48',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  {
    id: 'T_49',
    amount: 12300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },
  // Aug
  {
    id: 'T_50',
    amount: 2800000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_51',
    amount: 7300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_52',
    amount: 160000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_53',
    amount: 440000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_54',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_55',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: 'T_56',
    amount: 11500000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  // Sep
  {
    id: 'T_57',
    amount: 2500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_58',
    amount: 7500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_59',
    amount: 180000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_60',
    amount: 420000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_61',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_62',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  {
    id: 'T_63',
    amount: 12300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-01"),
  },
  // Oct
  {
    id: 'T_64',
    amount: 2500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_65',
    amount: 730000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_66',
    amount: 160000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_67',
    amount: 380000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_68',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_69',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  {
    id: 'T_70',
    amount: 12300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-01"),
  },
  // Nov
  {
    id: 'T_71',
    amount: 3100000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_72',
    amount: 7300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_73',
    amount: 165000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_74',
    amount: 370000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_75',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_76',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: 'T_77',
    amount: 14300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  // Dec
  {
    id: 'T_78',
    amount: 3100000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_79',
    amount: 7300000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_80',
    amount: 160000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_81',
    amount: 410000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_82',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_83',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: 'T_84',
    amount: 13300000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
];

export default transactions;
