import { Transaction } from '@prisma/client';
import { ECashflow, EPaymentMode } from '../../src/modules/transaction/transaction.enum';

const transactions: Transaction[] = [
  {
    id: 'T_1',
    amount: 3500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Eating, Drinking',
    categoryId: 'C_2',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_2',
    amount: 1100000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Electric Fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_3',
    amount: 160000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Water fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_4',
    amount: 450000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Gas fee',
    categoryId: 'C_4',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_5',
    amount: 1500000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CASH,
    description: 'Medicine',
    categoryId: 'C_8',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_6',
    amount: 1270000,
    cashflow: ECashflow.EXPENSE,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Health insurance',
    categoryId: 'C_7',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_7',
    amount: 13500000,
    cashflow: ECashflow.INCOME,
    paymentMode: EPaymentMode.CREDIT,
    description: 'Monthly Salary',
    categoryId: 'C_10',
    userId: 'US_1',
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default transactions;
